spring:
    application:
        name: Yollweb-service
    datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat,wall,log4j
      initalSize: 5
      maxActive: 10
      maxWait: 60000
    boot: #这是配置admin的地址，直接注册到admin中，（此种形式是通过spring-boot-admin-starter-client）
      admin:
        url: http://127.0.0.1:8888
    zipkin:
        base-url: http://127.0.0.1:9411 
    sleuth: 
        sampler:
          percentage: 1.0
        
server:
  port: 8080
 

feign: 
  hystrix: 
    enabled: true

mybatis:
  typeAliasesPackage: com.yollweb.springboot.cloud.service.domain
  mapperLocations: classpath:/mapper/**/*.xml


eureka:
  client:
    register-with-eureka: true
    service-url: 
      defaultZone: http://127.0.0.1:7001/eureka/

application: 
  druid: 
    username: admin
    password: admin1234
    
 
management.security.enabled: false   
#sc: 
#  redis: 
#    enable: true