server:
  port: 8888
spring:
  application:
    name: Yollweb-admin
  mail:
    host: smtp.qq.com
    username: 1209583157@qq.com
    password:
    properties: 
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  boot:
    admin:
      notify:
        mail:
          from: 1209583157@qq.com
          to: 1209583157@qq.com

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:7001}/eureka/
      #defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

management.security.enabled: false

