package com.yollweb.springboot.cloud.service2.impl.dao;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Update;
import java.util.List;
import java.util.Map;

@Mapper
public interface TMapper<T> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTION
     *
     * @mbg.generated Thu Nov 23 14:48:08 CST 2017
     */
    int insert(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTION
     *
     * @mbg.generated Thu Nov 23 14:48:08 CST 2017
     */
    List<T> selectAll();

    List<T> selectByExample(Map map);

    @Update("update T set is_change=true where series_no=#{value} limit 1")
    int updateIsChange(String seriesNo);
}
